{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoiceninja.fullname" . }}-secret
  labels:
    {{- include "invoiceninja.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.secret.appKey | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
  {{- if .Values.mysql.enabled }}
  DB_ROOT_PASSWORD: {{ .Values.secret.dbRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.dbRootPassword | quote }}
  {{- end }}
  IN_USER_EMAIL: {{ .Values.secret.inUserEmail | quote }}
  IN_PASSWORD: {{ .Values.secret.inPassword | quote }}
{{- end }}
