apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoiceninja.fullname" . }}-secret
  labels:
    {{- include "invoiceninja.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.secret.appKey | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  DB_ROOT_PASSWORD: {{ .Values.secret.dbRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.dbRootPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
  IN_USER_EMAIL: {{ .Values.secret.inUserEmail | quote }}
  IN_PASSWORD: {{ .Values.secret.inPassword | quote }}
