#!/bin/sh

FREQUENTY=`basename "$0"`
TIMESTAMP=$(date +"%Y-%m-%d")

case $FREQUENTY in

  daily)
    DAYS=6
    ;;

  weekly)
    DAYS=30
    find /backups -type f -name $TIMESTAMP-daily.sql.gz -delete
    ;;

  monthly)
    DAYS=122
    find /backups -type f -name $TIMESTAMP-weekly.sql.gz -delete
    ;;
esac

mysqldump -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} | gzip > /backups/$TIMESTAMP-$FREQUENTY.sql.gz

# Remove old backups
find /backups -mtime +${DAYS} -type f -name *-$FREQUENTY.sql.gz -delete

exit 0;